Pop window
ismailakinkunmi/portfolio-site pull request #17
Opened 2021-12-21 12:43 UTC by ismailakinkunmi

When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
When the user clicks (or taps) the close (X) button, the popup disappears,
You should implement popups for both mobile and desktop screen sizes.

2021-12-21 14:11 UTC, andersonlebon requested changes
### Hello @ismailakinkunmi 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your popup is responsive
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-21 14:11 UTC, andersonlebon commented on index.html
> +      <section class="form-section" id="contact">
### [OPTIONAL]
- [ ]  I would kindly suggest you increase the width of your contact form(inputs) in the mobile version.
correct this design below 👇  👇 
your design
![image](https://user-images.githubusercontent.com/65068771/146943548-6206c2ce-ee91-48b9-9383-bb5f5e3484a6.png)

2021-12-21 14:11 UTC, andersonlebon commented on js/main.js
> +              </a>
- [ ] I would recommend also kindly sticking to the design of these two buttons(height && width only).

The template | your design 
--------------|----------
![image](https://user-images.githubusercontent.com/65068771/146942574-bd8fdd2b-ca75-4f69-bf43-c7a970b44de5.png) | ![image](https://user-images.githubusercontent.com/65068771/146942915-ec749ba1-55b4-4fb3-9a21-9c8c33e2e62c.png)

2021-12-21 17:25 UTC, ismailakinkunmi commented
Thanks for the review, Those See buttons bug are clear to me but I can't
figure out anything at the tonic, canopy either desktop or mobile version,
i will suggest if you can take me through at zoom video for it, looking
forward to your response.

On Tue, Dec 21, 2021 at 3:11 PM anderson ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> Hello @ismailakinkunmi <https://github.com/ismailakinkunmi>
>
> Good job so far! I know you have worked hard on making this milestone But
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> [image: almost-there]
> <https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif>
> To highlight 🍾
>
>    - All linters are passing ✔️
>    - Good commit history ✔️
>    - Your design looks good 💯 ✔️
>    - Good PR description ✔️
>    - Your popup is responsive
>
> Required Changes ♻️
>
>    - Kindly check comments under the review.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In js/main.js
> <https://github.com/ismailakinkunmi/portfolio-site/pull/17#discussion_r773156150>
> :
>
> > +    <section class="modal-wrapper">
>
> +      <div class="modal">
>
> +        <div class="modal-title">
>
> +          <h2>${project.title}</h2>
>
> +          <div class='close-modal'>
>
> +          <span class="iconify" data-icon="ep:close-bold"></span>
>
> +          </div>
>
> +        </div>
>
> +        <div class="date">
>
> +            <h3>${project.subTitle}</h3>
>
> +                ${project.details
>
> +                  .map(
>
> +                    (
>
> +                      x
>
> +                    ) => ` <img src="img/Counter.png" alt="" class="counter" />
>
> +            <p>${x}</p>`
>
>
>
>    - God job on making your popup window responsive 👏 👏 however one of
>    the requirements says that you should stick to the template design, I can
>    see you forgot to align the title, subtitle as well as its details lthe way
>    they are aligned in the template. check the difference below 👇 👇
>
> Your design the template
> [image: image]
> <https://user-images.githubusercontent.com/65068771/146941251-3d745086-d44f-4cd8-bf5b-046a0bb3446a.png> [image:
> image]
> <https://user-images.githubusercontent.com/65068771/146941397-ce128458-09ef-4f8a-a820-59dfa1ddc99e.png>
> ------------------------------
>
> In index.html
> <https://github.com/ismailakinkunmi/portfolio-site/pull/17#discussion_r773160397>
> :
>
> >
>
>      <footer>
>
> -      <section class="form-section">
>
> +      <section class="form-section" id="contact">
>
>
> [OPTIONAL]
>
>    - I would kindly suggest you increase the width of your contact
>    form(inputs) in the mobile version.
>    correct this design below 👇 👇
>    your design
>    [image: image]
>    <https://user-images.githubusercontent.com/65068771/146943548-6206c2ce-ee91-48b9-9383-bb5f5e3484a6.png>
>
> ------------------------------
>
> In js/main.js
> <https://github.com/ismailakinkunmi/portfolio-site/pull/17#discussion_r773164972>
> :
>
> > +            <div class="modal-btns">
>
> +              <a href="${project.gitLink}" class="btn github-link">
>
> +                See live
>
> +                <span class="iconify iconbtn" data-icon="bytesize:github"></span>
>
> +              </a>
>
> +              <a href="${project.srcLink}" class="btn source-link">
>
> +                See source
>
> +                <span class="iconify iconbtnlink" data-icon="cil:external-link"></span>
>
> +              </a>
>
>
>
>    - I would recommend also kindly sticking to the design of these two
>    buttons(height && width only).
>
> The template your design
> [image: image]
> <https://user-images.githubusercontent.com/65068771/146942574-bd8fdd2b-ca75-4f69-bf43-c7a970b44de5.png> [image:
> image]
> <https://user-images.githubusercontent.com/65068771/146942915-ec749ba1-55b4-4fb3-9a21-9c8c33e2e62c.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ismailakinkunmi/portfolio-site/pull/17#pullrequestreview-837463272>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI5YZRV3LBY6QJMHYWMJXHTUSCDJJANCNFSM5KQCVCQQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2021-12-22 10:19 UTC, elyor-doniyorov approved these changes
Hi @andersonlebon, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-22 10:22 UTC, merged